# -*- coding: utf-8 -*-
"""create_relationshp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gTdsIdPh8FdlWBwOFc32nxR1sBwxHG8a
"""

import pandas as pd

csv_data = pd.read_csv ('/content/OcrData.csv')
group_data=df.groupby('Document Name')['Person Name'].apply(list)
from itertools import combinations
ocr_arr= []
for item in group_data:
  val=[",".join(map(str, comb)) for comb in combinations(item, 2)]
  for item1 in val:
    val1=item1.split(',')
    ocr_arr.append(val1)

print(ocr_arr)
simplified_ocrdata = pd.DataFrame(ocr_arr, columns = ['person1', 'person2'])
simplified_ocrdata.to_csv('SimplifiedOcrData.csv', index=False)

orig_data = pd.read_csv ('/content/OriginalData.csv')
orig_group_data=orig_data.groupby('Document Name')['Person Name'].apply(list)
orig_arr= []
for item in orig_group_data:
  val=[",".join(map(str, comb)) for comb in combinations(item, 2)]
  for item1 in val:
    val1=item1.split(',')
    orig_arr.append(val1)

print(orig_arr)
simplified_origdata = pd.DataFrame(orig_arr, columns = ['person1', 'person2'])
simplified_origdata.to_csv('SimplifiedOriginalData.csv', index=False)